### PR TITLE
Fixes the issue of showing track index 0 when getting a non-zero track

### PR DESCRIPTION
**Pull request by inancme**
Great project! A real life saver when moveslink would not sync. And so much faster. This is to fix an issue I noticed when retrieving a single track. The issue is not present when -1 is used. However let us say we want to retrieve the track 7. It will show the message "Retrieving track 0 ..." instead of "Retrieving track 7 ...". Thanks again for the project and keep the good work.

### CODE REVIEW

**Comment by iwanders** [comment]
Ah, yes, I see what you mean. Good catch. I think there's a better way to fix this though, without having to duplicate the print statement... what do you think about, at the start of the loop;

```python
        if (args.index == -1):
            tracks = enumerate(tracklist)
        else:
            tracks = [(args.index, tracklist[args.index])]

        for track_index, track in tracks:
```

I think that would solve it don't you think? If you agree it does, could you please update this PR to solve it in this way?

**Comment by iwanders** [comment]
> Great project! A real life saver when moveslink would not sync. And so much faster. 

Also, thanks, always happy to see code from years ago being put to good use by others! :+1: I never understood the intent of moveslink, requiring internet to change settings on the device... The internet is very far away when I need a GPS tracker... :) The hardware is superb... that's definitely something they got right.

**Comment by inancme** [comment]
Sure. I hope you don't mind if I do it next week as I am away from my
computer.

**Comment by inancme** [comment]
> Ah, yes, I see what you mean. Good catch. I think there's a better way to fix this though, without having to duplicate the print statement... what do you think about, at the start of the loop;
> 
> ```python
>         if (args.index == -1):
>             tracks = enumerate(tracklist)
>         else:
>             tracks = [(args.index, tracklist[args.index])]
> 
>         for track_index, track in tracks:
> ```
> 
> I think that would solve it don't you think? If you agree it does, could you please update this PR to solve it in this way?

https://github.com/iwanders/gps_track_pod/pull/4/commits/b818f115caf6ee8f2914b1ba58f3950eeb88a622

I have eliminated the extra branch.

**Comment by iwanders** [comment]
Looks good, thanks.

**Pull request merged**
